export { default as LoginPage } from "./AuthPages/LoginPage.tsx"
export { default as RegisterPage } from "./AuthPages/RegisterPage.tsx"
export { default as CardPage } from "./CardPage/CardPage.tsx"
export { default as CardsPage } from "./CardsPage.tsx"
export { default as CategoriesPage } from "./CategoriesPage.tsx"
export { default as CategoryPage } from "./CategoryPage.tsx"
export { default as HomePage } from "./HomePage.tsx"
export { default as UserAgreementPage } from "./UserAgreementPage.tsx"
